name: "Shelly Gen.1 update"
description: "Webinterface to update Shelly Gen.1 devices"
version: "0.0.1"
slug: "hello_world"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress_port: "5000"
ingress: true
ingress_entry: dashboard/
panel_title: "Shelly Gen.1"
