name: Shelly Firmware Updater
version: "1.0.2"
slug: shelly-firmware-updater
description: Shelly Gen. 2/3 API Device Scanner. Scanner will be looking for devices with new stable firmware update available.
panel_icon: "mdi:update"
url: "https://github.com/schulzrobin/ha-addons/tree/main/shelly-firmware-updater"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
init: false
ingress: true
ingress_port: 8099
options:
  ip_base: "192.168.5."
schema:
  ip_base: str
