name: Shelly Firmware Updater
version: "1.0.0"
slug: shelly-firmware-updater
description: Scannt Shelly-Geräte im LAN und stößt Firmware-Updates an (Ingress, Flask + gunicorn).
panel_icon: "mdi:update"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
init: false
ingress: true
ingress_port: 8099
options:
  ip_base: "192.168.5."
schema:
  ip_base: str
