name: Shelly Firmware Updater
version: "1.0.1"
slug: shelly-firmware-updater
description: Scannt Shelly-Geräte im LAN und stößt Firmware-Updates an (Ingress, Flask + gunicorn).
arch:
  - aarch64
  - amd64
  - armv7
startup: services
init: false
ingress: true
ingress_port: 8099
panel_title: Shelly Updater
panel_icon: mdi:update
options:
  ip_base: "192.168.5."
schema:
  ip_base: str
