name: Shelly Firmware Updater
version: "1.0.0"
slug: shelly-firmware-updater
description: Scannt Shelly-Geräte im LAN und stößt Firmware-Updates an (Ingress, Flask + gunicorn).
arch:
  - aarch64
  - amd64
  - armv7
startup: services
init: false
ingress: true
ingress_port: 8099
panel_title: Shelly Updater
panel_icon: mdi:update
map:
  - config:rw
  - ssl:rw
  - share:rw
  - media:rw
  - addons:rw
  - backup:rw
  - data:rw
options:
  ip_base: "192.168.5."
schema:
  ip_base: str
image: "local/shelly_firmware_updater:{arch}-1.0.0"