name: "Einkaufsliste"
description: Einfache Einkaufsliste mit SQL Datwnbank.
version: "1.0.0"
slug: "einkaufsliste"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ingress_port: 8099