name: "Einkaufsliste"
version: "1.0.0"
slug: "einkaufsliste"
description: "Einfache Einkaufsliste"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
init: false
ingress: true
ingress_port: 8099
panel_icon: "mdi:cart"
options: {}
schema: {}
