name: "Example Ingress Python3"
description: "Beispiel Add-on mit Python Backend und Ingress"
version: "1.0.5"
slug: "example_ingress"
init: false

arch:
  - amd64
  - armv7
  - armhf
  - aarch64
  - i386

startup: services
boot: auto

ingress: true
ingress_port: 8099
ingress_entry: /
panel_icon: mdi:python
panel_title: Python Add-on

options: {}
schema: {}

ports: {}
ports_description: {}